In [1]:
import pandas as pd

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [3]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [4]:
df.head(15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0

In [5]:
df.tail(15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2985,-120.47,34.94,17.0,1368.0,308.0,642.0,303.0,1.8633,109400.0
2986,-118.25,33.93,42.0,819.0,233.0,899.0,228.0,1.1346,85400.0
2987,-121.97,37.29,25.0,4096.0,743.0,2027.0,741.0,5.3294,300300.0
2988,-122.01,36.97,43.0,2162.0,509.0,1208.0,464.0,2.5417,260900.0
2989,-122.02,37.60,32.0,1295.0,295.0,1097.0,328.0,3.2386,149600.0
2990,-118.23,34.09,49.0,1638.0,456.0,1500.0,430.0,2.6923,150000.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [6]:
df = pd.read_csv("/content/Salaries.csv")

In [7]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [8]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [9]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [11]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [12]:
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [14]:
df["rank"]

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [16]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [17]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [18]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            57800
dtype: object

In [20]:
df[['phd', 'service', 'salary']].mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [21]:
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [22]:
df.phd.quantile(0.25)

np.float64(10.25)

In [23]:
df.salary.quantile(0.50)

np.float64(104671.0)

In [24]:
df.salary.quantile(0.75)

np.float64(126774.75)

In [25]:
df[['phd', 'service', 'salary']].std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [26]:
df_50 = df.head(50)

In [28]:
df_50[['phd', 'service', 'salary']].mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [29]:
df_50

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960

In [30]:
df.salary

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [31]:
df["salary"]

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [32]:
result1 = df.salary

In [34]:
result1

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [35]:
type(result1)

pandas.core.series.Series

In [36]:
result2 = df[["salary","rank"]]

In [37]:
result2

    salary       rank
0   186960       Prof
1    93000       Prof
2   110515       Prof
3   131205       Prof
4   104800       Prof
..     ...        ...
73  105450       Prof
74  104542  AssocProf
75  124312       Prof
76  109954       Prof
77  109646       Prof

[78 rows x 2 columns]

In [38]:
type(result2)

pandas.core.frame.DataFrame

In [39]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [40]:
new_df = [["salary","service","phd"]]

In [41]:
new_df

[['salary', 'service', 'phd']]

In [42]:
df.discipline.value_counts()

discipline
B    42
A    36
Name: count, dtype: int64

In [43]:
df["rank"].value_counts()

rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

In [44]:
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [45]:
df.phd.count()

np.int64(78)

In [46]:
df.phd.mean()

np.float64(19.705128205128204)

In [48]:
df.groupby(['rank'])[['phd', 'service', 'salary']].mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [49]:
df.groupby(['sex'])[['phd', 'service', 'salary']].mean()

              phd    service         salary
sex
Female  16.512821  11.564103  101002.410256
Male    22.897436  18.538462  115045.153846

In [50]:
df.groupby(["discipline"]).count()

            rank  phd  service  sex  salary
discipline
A             36   36       36   36      36
B             42   42       42   42      42

In [51]:
df.groupby(["discipline","rank"]).count()

                      phd  service  sex  salary
discipline rank
A          AssocProf    5        5    5       5
           AsstProf     8        8    8       8
           Prof        23       23   23      23
B          AssocProf    8        8    8       8
           AsstProf    11       11   11      11
           Prof        23       23   23      23

In [52]:
df.groupby(["discipline","rank","sex"]).count()

                             phd  service  salary
discipline rank      sex
A          AssocProf Female    4        4       4
                     Male      1        1       1
           AsstProf  Female    6        6       6
                     Male      2        2       2
           Prof      Female    8        8       8
                     Male     15       15      15
B          AssocProf Female    6        6       6
                     Male      2        2       2
           AsstProf  Female    5        5       5
                     Male      6        6       6
           Prof      Female   10       10      10
                     Male     13       13      13

In [53]:
df.groupby(["discipline","rank","sex"]).mean()

                                   phd    service         salary
discipline rank      sex
A          AssocProf Female  18.500000  15.500000   72128.500000
                     Male    20.000000  17.000000   81285.000000
           AsstProf  Female   4.833333   2.500000   72933.333333
                     Male     3.000000   1.000000   79000.000000
           Prof      Female  26.500000  16.125000  109631.875000
                     Male    28.933333  22.733333  113164.400000
B          AssocProf Female  13.500000   8.833333   99435.666667
                     Male    10.500000   7.500000  113404.000000
           AsstProf  Female   6.600000   2.600000   84189.800000
                     Male     4.666667   2.000000   88224.000000
           Prof      Female  21.500000  17.900000  131836.200000
                     Male    29.538462  25.846154  137989.076923

In [54]:
df.groupby("rank")[["salary","phd"]].mean()

                  salary        phd
rank
AssocProf   91786.230769  15.076923
AsstProf    81362.789474   5.052632
Prof       123624.804348  27.065217

In [55]:
grouped = df.groupby("rank")

In [56]:
grouped

In [57]:
for g in grouped:
  print(g)

('AssocProf',          rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542)
('AsstProf',         rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
50  AsstProf          B   10        5  Female   97032
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
66  AsstProf          A    7        6  Female   63100
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500)
('Prof',     rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646)

In [58]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [59]:
df.shape

(78, 6)

In [60]:
df.shape[0]

78

In [61]:
df.shape[1]

6

In [62]:
df[df.salary>120000].shape[0]

25

In [63]:
df[df.salary>120000].count()

rank          25
discipline    25
phd           25
service       25
sex           25
salary        25
dtype: int64

In [71]:
newdf = df[(df.salary>150000) & (df["sex"]=="Male")]

In [72]:
newdf

    rank discipline  phd  service   sex  salary
0   Prof          B   56       49  Male  186960
13  Prof          B   35       33  Male  162200
14  Prof          B   25       19  Male  153750
15  Prof          B   17        3  Male  150480
19  Prof          A   29       27  Male  150500
27  Prof          A   45       43  Male  155865
31  Prof          B   22       21  Male  155750

In [73]:
newdf.shape[0]

7

In [74]:
df[(df["service"]>15) | (df['salary']>100000 )]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
69       Prof          A   28        7  Female  116450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [76]:
df.iloc[77]

rank            Prof
discipline         A
phd               23
service           15
sex           Female
salary        109646
Name: 77, dtype: object

In [77]:
df.iloc[1:4, 0:3]

   rank discipline  phd
1  Prof          A   12
2  Prof          A   23
3  Prof          A   40

In [78]:
df.iloc[0:10, 0:3]

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [79]:
df.iloc[0:2 ,]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000

In [80]:
df.iloc[:,4]

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
73    Female
74    Female
75    Female
76    Female
77    Female
Name: sex, Length: 78, dtype: object

In [81]:
df.iloc[:, 0:3]

         rank discipline  phd
0        Prof          B   56
1        Prof          A   12
2        Prof          A   23
3        Prof          A   40
4        Prof          B   20
..        ...        ...  ...
73       Prof          B   18
74  AssocProf          B   19
75       Prof          B   17
76       Prof          A   28
77       Prof          A   23

[78 rows x 3 columns]

In [82]:
df.iloc[[10,20,30,40],]

         rank discipline  phd  service     sex  salary
10       Prof          B   39       33    Male  128250
20   AsstProf          B    4        4    Male   92000
30  AssocProf          B    9        7    Male  107008
40       Prof          A   39       36  Female  137000

In [83]:
df.loc[:,["rank","sex"]]

         rank     sex
0        Prof    Male
1        Prof    Male
2        Prof    Male
3        Prof    Male
4        Prof    Male
..        ...     ...
73       Prof  Female
74  AssocProf  Female
75       Prof  Female
76       Prof  Female
77       Prof  Female

[78 rows x 2 columns]

In [86]:
df.loc[[0,1,2,5],["rank","sex"]]

   rank   sex
0  Prof  Male
1  Prof  Male
2  Prof  Male
5  Prof  Male

In [87]:
df.iloc[::5]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
5        Prof          A   20       20    Male  122400
10       Prof          B   39       33    Male  128250
15       Prof          B   17        3    Male  150480
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
30  AssocProf          B    9        7    Male  107008
35       Prof          B   28       23    Male  126933
40       Prof          A   39       36  Female  137000
45       Prof          B   25       25  Female  140096
50   AsstProf          B   10        5  Female   97032
55   AsstProf          A    2        0  Female   72500
60   AsstProf          B    3        3  Female   92000
65       Prof          A   36       19  Female  117555
70   AsstProf          A    8        3  Female   78500
75       Prof          B   17       17  Female  124312

In [88]:
df.iloc[10:30:4]

        rank discipline  phd  service   sex  salary
10      Prof          B   39       33  Male  128250
14      Prof          B   25       19  Male  153750
18      Prof          A   19        7  Male  107300
22  AsstProf          A    4        2  Male   73000
26      Prof          A   38       19  Male  148750

In [89]:
df.iloc[::-1]

         rank discipline  phd  service     sex  salary
77       Prof          A   23       15  Female  109646
76       Prof          A   28       14  Female  109954
75       Prof          B   17       17  Female  124312
74  AssocProf          B   19        6  Female  104542
73       Prof          B   18       10  Female  105450
..        ...        ...  ...      ...     ...     ...
4        Prof          B   20       18    Male  104800
3        Prof          A   40       31    Male  131205
2        Prof          A   23       20    Male  110515
1        Prof          A   12        6    Male   93000
0        Prof          B   56       49    Male  186960

[78 rows x 6 columns]

In [90]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'discipline',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'phd',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'service',
 'set_axis',
 'set_flags',
 'set_geometry',
 'set_index',
 'sex',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [92]:
df[["phd","salary"]].agg(["min","max","mean","std"])

            phd         salary
min    1.000000   57800.000000
max   56.000000  186960.000000
mean  19.705128  108023.782051
std   12.498425   28293.661022

In [93]:
df[["salary"]].agg("kurt")

salary   -0.401713
dtype: float64

In [97]:
df[["salary"]].agg("skew")

salary    0.452103
dtype: float64